### ISSUE TITLE
channel:opened event not firing

### ISSUE THREAD

**Issue by davidbanham** [rtc-io/rtc-quickconnect#35]
Repro below with the example code from the README. This is tested in both Chrome and Firefox Developer Edition. There are no error messages and nothing that appears useful in the debug output.

```javascript
var freeice = require('freeice');
var quickconnect = require('rtc-quickconnect');
var opts = {
  room: 'qcexample-dctest',
  // debug: true,
  iceServers: freeice()
};

quickconnect('http://rtc.io/switchboard/', opts)
  // tell quickconnect we want a datachannel called test
  .createDataChannel('test')
  // when the test channel is open, let us know
  .on('channel:opened:test', function(id, dc) {
    dc.onmessage = function(evt) {
      console.log('peer ' + id + ' says: ' + evt.data);
    };

    console.log('test dc open for peer: ' + id); // This never fires.
    dc.send('hi');
  });
```

**Comment by DamonOehlman** [comment]
Hmmm, thanks David - will look into it ASAP.  I just tested the first example in the "secret" (poorly advertised) guidebook and it works between two local connections:

http://guidebook.rtc.io/DataChannels.md

Any special network conditions to speak of between the two in your case?

**Comment by davidbanham** [comment]
I had the two browsers running on the same computer. Tried that on two
different networks and against three different installations of the
rtc-switchboard software.

I am very prepared to be told I'm Doing It Wrong.

**Comment by davidbanham** [comment]
I also just tried the first example in the guidebook and it's failing on both browsers on my machine. Is this an OSX issue, something with my laptop, or a failure in my method? The test I'm using is to open the following page and wait for the "has opened a data channel for comms" log statement, which never comes.

```javascript
var quickconnect = require('rtc-quickconnect');
var uuid = require('uuid');
var roomId = uuid.v4();

// create some peers
var peerA = quickconnect('//switchboard.rtc.io/', { room: roomId });
var peerB = quickconnect('//switchboard.rtc.io/', { room: roomId });

// tell the peers that we want data channels
peerA.createDataChannel('test');
peerB.createDataChannel('test');

peerA.on('channel:opened:test', function(id, dc) {
  console.log('peer A has opened a data channel for comms with peer: ' + id);

  dc.onmessage = function(evt) {
    console.log('peer A received a message: ' + evt.data);
  };

  dc.send('hello');
});

peerB.on('channel:opened:test', function(id, dc) {
  console.log('peer B has opened a data channel for comms with peer: ' + id);

  dc.onmessage = function(evt) {
    console.log('peer B received a message: ' + evt.data);
  };

  dc.send('hi');
});

console.log('peer A created with id: ' + peerA.id);
console.log('peer B created with id: ' + peerB.id);
```

```html
<html>
<head>
<title>Event Repro</title>
</head>
<body>
<script src="guide.js"></script>
</body>
</html>
```

**Comment by davidbanham** [comment]
The above code also failed in 3.0.0, but worked correctly in 2.0.0

```
rtc-quickconnect@2.0.0 node_modules/rtc-quickconnect
├── cog@1.0.0
├── rtc-core@1.3.1 (semver@2.3.2)
├── rtc-tools@2.3.1 (normalice@1.0.1, eventemitter3@0.1.6, async@0.9.0, rtc-core@3.2.0)
└── rtc-signaller@2.5.1 (formatter@0.4.1, eventemitter3@0.1.6, rtc-core@3.2.0, ws@0.4.32)
```

**Comment by DamonOehlman** [comment]
Does it work with the quickconnect 4.x series?  That's what I'm usually testing against these days. 2.x is pretty solid too (just a bit different under hood).  I think I may have created the equivalent of Windows Vista with quickconnect 3.0 :/

**Comment by DamonOehlman** [comment]
Also, probably worth opening up <chrome://webrtc-internals> and seeing what you see.  Ideally you are looking for the `iceConnectionState` on the connections to hit `connected` or `completed`.

**Comment by davidbanham** [comment]
Yep, it fails on both 4.x and 3.x for me.

I have no idea what I'm looking at with the webrtc-internals page. The top screenshot is 4.x, the bottom screenshot is 2.x.

![screen shot 2015-01-14 at 10 54 15 am](https://cloud.githubusercontent.com/assets/631832/5731782/c723d1d6-9bdb-11e4-9d0c-d143768c02d9.png)
![screen shot 2015-01-14 at 10 51 50 am](https://cloud.githubusercontent.com/assets/631832/5731781/c722f0f4-9bdb-11e4-9eba-fc4c78acd9af.png)

**Comment by davidbanham** [comment]
Ooh, also, on the 4.x branch I see this console.error when the page has been open for something like 60 seconds. I do not see this in the 2.x branch.

WebSocket connection to 'ws://rtc.io/switchboard/' failed: Error during WebSocket handshake: Unexpected response code: 404

**Comment by DamonOehlman** [comment]
I think that is probably ok - the signaller just tries two endpoints to deal with me changing some stuff with `rtc-switchboard`, and this gives it compatibility with both versions.  If you can do the following using a test for 4.x I can probably dig into to what is happening:

1. Close down all browser tabs that have been attempting to create peer connections
2. Open <chrome://webrtc-internals> - you should be able to see a "Create Dump" link that will allow you to download a log file of everything that has gone on.
3. Run a test using quickconnect 4.x
4. Hit the "Download the PeerConnection..." button and save the log to your machine.
5. Email me the log (damon.oehlman -at- gmail.com)

**Comment by davidbanham** [comment]
Dump generated and email sent.

**Comment by DamonOehlman** [comment]
Thanks David - I've tracked it down and it's related to a change I made in rtc-taskqueue (which explains why rtc-quickconnect@2 is not affected).  Fixing it now.

**Comment by DamonOehlman** [comment]
All done.  If you can remove rtc-quickconnect and re-install it should pick up the new version of rtc-taskqueue (2.4.4) and all should be well again.  Sorry for stuffing you around...

**Comment by davidbanham** [comment]
Fix confirmed, thanks!

I wonder why this wasn't picked up by the test case, though.

https://github.com/rtc-io/rtc-quickconnect/blob/master/test/events.js#L28

**Comment by DamonOehlman** [comment]
I was wondering the same thing.  While a travis build of quickconnect wouldn't be triggered by a rtc-taskqueue update, I thought I manually kicked off a job after making this change.  I guess I mustn't have.  I'll definitely investigate scheduling daily tests of rtc-quickconnect (and friends) so I find this stuff out prior to a bug report being filed...

Thanks again for reporting it :)

**Comment by davidbanham** [comment]
No sweat. Thanks for writing a useful, modular set of libraries and open-sourcing them.
