### ISSUE TITLE
Connection over socket.io?

### ISSUE THREAD

**Issue by Neograph734** [rtc-io/rtc-quickconnect#38]
I've been looking for several days for this, but no luck, so I am just going to ask... Should it be possible to send the messages over socket.io, and are there any hints on how to do so?

I am asking because I have an existing infrastructure that handles authentication and rooms over socket.io. I'd like to preserve this while adding webrtc to the system, which I could not by using the default Primus implementation.

If I understood the code correct I can override the default messenger by calling rtc-quickconnect() and providing a function as the first parameter. This function replaces the rtc-switchboard-messenger and should eventually return a function to create a pull_stream as defined in https://github.com/DamonOehlman/messenger-archetype.

Are you aware of any kind of pull_stream wrapper that works on socket.io connections rather than plain websockets? Is such a thing possible?

**Comment by DamonOehlman** [comment]
Should definitely be possible, and probably not too complicated.  Just so you are aware, we've been doing a little bit of analysis internally on the current signalling and we'll be pushing out some changes over the next couple of weeks.  What are your timelines for requiring something?

More than happy to talk through some of those protocol changes and look at how that could be made to work with socket.io at the same time if that's of interest.  Just ping me an email and I'll get the ball rolling on that next week.

**Comment by Neograph734** [comment]
Thanks for the reply. I'd be happy to have such a thing in a week of 4-5, but I am already happy I've found a webRTC system that actually works. So please take all the time you need to make it better. I'll send you a mail in a week or so.

**Comment by DamonOehlman** [comment]
As discussed this is now possible using the [`rtc-signaller-socket.io`](https://github.com/rtc-io/rtc-signaller-socket.io) package, see the usage example on the README:

https://github.com/rtc-io/rtc-signaller-socket.io#client
