### ISSUE TITLE
Firefox cannot establish a connection to switchboard

### ISSUE THREAD

**Issue by mattvv** [rtc-io/rtc-quickconnect#39]
I'm getting the following:

```
Firefox can't establish a connection to the server at wss://switchboard.rtc.io/.
```

Everything seems fine in Chrome. I went to the trouble of setting up my own switchboard server on elastic beanstalk and ended up with the exact same results. Fine on Chrome, this error on firefox. Any tips?

**Comment by silviapfeiffer** [comment]
Maybe you have to accept the certificate for the websocket server first? http://stackoverflow.com/questions/11542460/secure-websocket-wss-doesnt-work-on-firefox

**Comment by DamonOehlman** [comment]
@silviapfeiffer This sounds like a problem similar to what you described the other day with another of our gandi wildcard certs.  I'm going to look at implementing the instructions as outlined [here](http://wiki.gandi.net/en/ssl/intermediate) (regarding the Comodo cross signed certificate) and see if that makes a difference.

**Comment by silviapfeiffer** [comment]
ah, oops, it's our server! Indeed! Sorry for the confusion.

**Comment by mattvv** [comment]
Are you suggesting this is a cert issue? I have my own server set up with a Comodo Cert that has a similar issue.

**Comment by DamonOehlman** [comment]
I've been having a look at this recently (ensuring our certs are correct etc) and it's possible it isn't.  In recent changes to [`rtc-signaller`](https://github.com/rtc-io/rtc-signaller) I added functionality that attempted connectivity with two websocket endpoints (one after the other).  The first endpoint that is tried is `wss://host/` and if that fails it then attempts to connect to `wss://host/primus`.  I did this as I intend to move away from primus in `rtc-switchboard` but wanted to make sure the transition was as smooth as possible.

One of the side effects of doing this, however, has been a nasty red error message that pops up reporting failed socket connections (even though this is being handled gracefully in the code).

This error is usually also visible in Chrome, so if you are reporting Chrome as working it may not be the above either.  Regardless happy to work through this until we've got it sorted.

**Comment by mattvv** [comment]
I do see the error messages in chrome every so often for 404 not found, so this could be the same issue, although Firefox ay be displaying it differently.

**Comment by mattvv** [comment]
Confirming this again it looks like Firefox can connect, but this is just an error message most likely due to your migration above. I think the reasoning of it not connecting sometimes may be related to #40 and chrome not getting a correct ICE candidate.
