### ISSUE TITLE
Handling ICE Issues

### ISSUE THREAD

**Issue by mattvv** [rtc-io/rtc-quickconnect#40]
Hey Guys,

Just wondering the best way to handle ICE issues in my application. Every so often I get

```
 addIceCandidate task failed:  Error processing ICE candidateindex.js:126 (anonymous function)index.js:90 handleFail
```

This leaves the user with either no sound at all (in the case of a 2 person call) or in some cases a call where you can hear some members but not others.

What's the best way to handle this? I tried adding my own list of stun servers in the iceServers configuration with no avail. I even spun up my own TURN server to try and handle this, however it seems to happen even locally when I have no issues with firewalls connecting from my local machine to my local machine.

Thanks,

Matt

**Comment by DamonOehlman** [comment]
@mattvv It's possible that the invalid candidate can be handled (not applied until it is valid) within [`rtc-taskqueue`](https://github.com/rtc-io/rtc-taskqueue) but I'd probably need more information on what that candidate looks like.

If you can follow the instructions I've outlined [here in another issue](https://github.com/rtc-io/rtc-quickconnect/issues/35#issuecomment-69853837) I should be able to track down the problem and ensure the case is properly catered for.

**Comment by mattvv** [comment]
Thanks mate!
Good instructions:

Here's the problem that occurs randomly (https://www.dropbox.com/s/x8cr27ig24q77nn/Screenshot%202015-02-24%2018.22.05.png?dl=0). Seems to happen maybe 1/2 the time if I refresh.

Let me know if you need a dump of me reproducing this.

**Comment by DamonOehlman** [comment]
Thanks for that screenshot.  I think the most likely cause of the failure will be to do with the connection wanting to renegotiate right before the ice candidate is applied, as I've seen definitely seen the signaling state of a peer connection have an impact on this previously.

I'd certainly like to code up a test case which reproduces what is happening in your case.  Do you think it would be possible to recreate what you are doing and post it in a gist so I can do some further analysis?

**Comment by silviapfeiffer** [comment]
I think this has since been addressed. Re-open if you're still having issues.
