### ISSUE TITLE
Testing several browsers simultaneously 

### ISSUE THREAD

**Issue by diasdavid** [rtc-io/rtc-quickconnect#43]
Hi @DamonOehlman ! Got your ping from https://github.com/webrtcftw/goals/issues/8#issuecomment-77729454, this looks very interesting indeed, thank you!

If I understand correctly, I could replace the `testling` for [`piri-piri`](https://github.com/diasdavid/piri-piri)* but I would still need to spawn several browsers in one travis-ci run. If also I understand correctly, what the 'matrix' property in travis-ci.yml does is running through the tests for each browser you selected (not all at the same time), right?

Do you have any idea of how to spawn several browsers in one run? Even tabs would be fine :)

* `piri-piri` is just a testing hack I did in order to aggregate the state of all the peers and do my inferences (tests) on the server side

**Comment by DamonOehlman** [comment]
Hey David - thanks for responding :)  I saw what you had been working on recently (piri-piri was the most relavant but your webrtc-ring experiment was also really interesting).

I'm fairly certain I can work out how to spawn multiple browsers as part of a single CI job, and you are right the current matrix configuration tells travis to create n jobs from a single core repo.   This has been really good in terms of checking an individual browser's support for the stuff we are doing with rtc.io, but it has never covered off the interop test cases.

This week, I'll work towards getting to a point where a single travis CI job can spawn multiple browsers and then we should definitely talk about integrating piri-piri :)

**Comment by silviapfeiffer** [comment]
Closing, because it's likely not relevant any longer. Please re-open if you need this sorted out still.
