### ISSUE TITLE
Any known impact of upcoming Chrome 44 release

### ISSUE THREAD

**Issue by jawandarajbir** [rtc-io/rtc-quickconnect#49]
Hi Damon,

As you might be aware of next chrome version bring major changes to webrtc api -
https://groups.google.com/forum/#!msg/discuss-webrtc/mrLyXc6Y464/sxuFb-qb4u0J

So far, we have made couple of test calls between chrome 43 (stable) and chrome 44 (beta) . It looks good so far.

Are you aware of any impact of this chrome release on rtc.io ? 
Are there any tests you can think of that we can run in order to be better prepared for Chrome 44?

Thanks, 
Raj

**Comment by DamonOehlman** [comment]
Hey Raj - having a read of the notes I think this is going to primarily need manual testing to ensure a high level of confidence.  While the whole rtc.io suite is pretty strong with regards to connectivity testing, it is definitely not as strong with regards to validating capture works and media is transmitted over the wire and received as expected by the remote endpoint.

From my reading of the notes though, even though they use the words "Video API" it doesn't seem that the surface of the WebRTC or Media Capture APIs are being effected in this change, just underlying implementations.  Is this correct?  I'm guessing they use the phrase API for those folks who are using "libwebrtc" and building something on top of it.  So maybe @wangzhen263 will have some stuff to do...

My gut feeling is that from an rtc.io perspective, most things should be fine, but I'd definitely give things a solid once over to be sure.  Something I'll definitely take a look at.

cc @silviapfeiffer

**Comment by jawandarajbir** [comment]
Thanks @DamonOehlman 
I also found the same in testing so far. The changes are mostly in underlying implementations. Things on surface are working quite smoothly.

I'll keep you posted if we find anything interesting.

**Comment by DamonOehlman** [comment]
Cool - thanks Raj :)
