### ISSUE TITLE
Connecting to a turn server

### ISSUE THREAD

**Issue by Neograph734** [rtc-io/rtc-quickconnect#53]
Hi Damon,

I recently ran into an issue where my connection to a turn server appears to be failing, and I suppose it is my configuration. Could you check if it is supposed to work like this?

```
conference = RTC({
  constraints: {
    audio: true,
    video: true
  },
  signaller: signaller,
  room: room,
  ice: [
    {url: "stun:server.foo:3478"},
    {
      url: "turn:server.foo:3478",
      username: "turnuser",
      credential: "turnpassword",
    },
  ],
  localContainer: '#localVideo',
  remoteContainer: '#remoteVideo',
  options: {}
});
```

ice configuration is based on http://www.html5rocks.com/en/tutorials/webrtc/infrastructure/

```
{
  'iceServers': [
    {
      'url': 'stun:stun.l.google.com:19302'
    },
    {
      'url': 'turn:192.158.29.39:3478?transport=udp',
      'credential': 'JZEOEt2V3Qb0y27GRntt2u2PAYA=',
      'username': '28224511:1379330808'
    },
    {
      'url': 'turn:192.158.29.39:3478?transport=tcp',
      'credential': 'JZEOEt2V3Qb0y27GRntt2u2PAYA=',
      'username': '28224511:1379330808'
    }
  ]
}
```

**Comment by nathanoehlman** [comment]
Hi @Neograph734,

Not Damon but I may be able to help. It looks like you're doing everything right - however, TURN ICE servers generally need to be specified with the transport type (ie. `turn:server.foo:3478?transport=udp`), with individual entries for both TCP and UDP (if your TURN server supports them both).

Let me know if you're still having issues.

Cheers,
Nathan

**Comment by Neograph734** [comment]
Thanks for the reply. I've updated as you suggested and will see what happens.

**Comment by Neograph734** [comment]
I was running the [Coturn](https://github.com/coturn/coturn) server which requires the username to be in the url, so I had to do it like this: 

```
{
  url: "turn:username@server.foo:3478",
  credential: "turnpassword",
}
```

But thanks for the response!
