### ISSUE TITLE
TypeError: PeerConnection is not a function

### ISSUE THREAD

**Issue by stephen304** [rtc-io/rtc-quickconnect#66]
I'm getting this error when running the example in the readme. I made an empty folder with `package.json`

    {
      "name": "rtc-test",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC",
      "dependencies": {
        "rtc-quickconnect": "^5.2.1"
      }
    }

and `index.js` copied from the readme:

    var quickconnect = require('rtc-quickconnect');
    
    quickconnect('https://switchboard.rtc.io/', { room: 'qc-simple-demo' })
      .on('call:started', function(id, pc, data) {
        console.log('we have a new connection to: ' + id);
      });

Did `npm install` then `node index.js` in 2 terminals:

    stephen@Jupiter ~/git/stephen304.com/rtc-test (git)-[master] % node index.js
    /home/stephen/git/stephen304.com/rtc-test/node_modules/rtc-tools/index.js:88
      return new PeerConnection(config, constraints);
             ^
    
    TypeError: PeerConnection is not a function
        at Object.exports.createConnection (/home/stephen/git/stephen304.com/rtc-test/node_modules/rtc-tools/index.js:88:10)
        at /home/stephen/git/stephen304.com/rtc-test/node_modules/rtc-quickconnect/index.js:227:16
        at module.exports (/home/stephen/git/stephen304.com/rtc-test/node_modules/rtc-core/genice.js:29:3)
        at connect (/home/stephen/git/stephen304.com/rtc-test/node_modules/rtc-quickconnect/index.js:218:5)
        at /home/stephen/git/stephen304.com/rtc-test/node_modules/rtc-quickconnect/index.js:430:5
        at /home/stephen/git/stephen304.com/rtc-test/node_modules/mbus/index.js:40:22
        at Array.map (native)
        at bus (/home/stephen/git/stephen304.com/rtc-test/node_modules/mbus/index.js:39:35)
        at /home/stephen/git/stephen304.com/rtc-test/node_modules/rtc-signal/handlers/announce.js:64:14
        at /home/stephen/git/stephen304.com/rtc-test/node_modules/rtc-signal/process.js:92:11

Any ideas?

**Comment by olexme** [comment]
I have the same issue. Any workarounds  ?

**Comment by DamonOehlman** [comment]
Hey folks - this will be because without an appropriate plugin quickconnect will not work in a node environment.   Try taking a look at the example in the `rtc-plugin-node` repo:

https://github.com/rtc-io/rtc-plugin-node#example-usage

Going to clone that repo now and make sure it all still works, and whether the version of the [https://github.com/js-platform/node-webrtc](`node-webrtc`) dependency needs updating.

**Comment by DamonOehlman** [comment]
OK, so it does work (I upgraded the `devDependencies` of the package to the latest `rtc-quickconnect` versions) but the only node version I could use that successfully worked with the `wrtc` package on Mac was `0.10`.  As such, something like [https://github.com/creationix/nvm](`nvm`) is recommended to experiment with the sample.
