### ISSUE TITLE
Announce contains the user id of the person starting the call not who is announcing

### ISSUE THREAD

**Issue by magestican** [rtc-io/rtc-quickconnect#71]
Client1 announces client2 of his existence, client2 then announces yes im also here, lets connect, but client2 passes client1 id and not his in the announce which is not right

**Comment by nathanoehlman** [comment]
Hi Bryan,

I'm not seeing this behaviour.

Using the `example/datachannel.js` test, I get the following:

Peer 1 (signaller ID = cim2ub79t00003j5509z77pb9) announces with
```/announce|cim2ub79t00003j5509z77pb9|{"browser":"chrome","browserVersion":"49.0.2623","agent":"signaller@6.3.0","id":"cim2ub79t00003j5509z77pb9","room":"qcexample-dctest"}```

Peer 2 (signaller ID = cim2ubla100003j55otkbamq1) announces with the correct signaller ID in
```/announce|cim2ubla100003j55otkbamq1|{"browser":"chrome","browserVersion":"49.0.2623","agent":"signaller@6.3.0","id":"cim2ubla100003j55otkbamq1","room":"qcexample-dctest"}```

Peer 1 sends a targeted announce to Peer 2 with it's correct signaller IDs using 
```/to|cim2ubla100003j55otkbamq1|/announce|cim2ub79t00003j5509z77pb9|{"browser":"chrome","browserVersion":"49.0.2623","agent":"signaller@6.3.0","id":"cim2ub79t00003j5509z77pb9","room":"qcexample-dctest"}```

If you've got some copies of the announce messages that have the erroneous id that would help get to the bottom of this.

Cheers,
Nathan

**Comment by magestican** [comment]
Hey Nathan, thank you for your response, it was my mistake, I was parsing the raw data sent from quickconnect in my server side socket.io component and I did not know there were  /to messages which contained /announce afterwards and that caused a big mess in my code, thanks for clarification
