### ISSUE TITLE
On 3 way call the number of messages sent to signaller server increases at least 4 times until it stabilizes or fails

### ISSUE THREAD

**Issue by magestican** [rtc-io/rtc-quickconnect#72]
So I am having an issue where in 3 way call the number of messages sent to the server by quickconnect increases by a huge margin, and depending on internet connection speed this causes an unstable video call.
4 way call is almost impossible because of this and mobile call due to processor speed is also very unreliable.

2 way calls are perfect but still there are many more messages being sent than in previous versions of quickconnect(2.7). 

Is there any way to throttle the number of messages being sent to the signaller server? There are many messages that seem irrelevant like multiple (10-20) "ping" and "ready" messages being sent every 10 seconds.

**Comment by nathanoehlman** [comment]
Hi @magestican,

I'll take a look into this - the number of messages being sent has increased with the newer versions of quickconnect (as a result of a number of various reasons) but the increase in messages should be linear, as opposed to exponential - so if it's exponential then something bad is happening. 

I'll let you know what I find out.

Cheers,
Nathan

**Comment by magestican** [comment]
Hey Nathan, I finally know why this is happening and will create a separate issue with the description. It has to do with emiting messages to a room rather than each participant and so people who shouldnt get messages do get them
