### ISSUE TITLE
 Failed to set remote offer sdp

### ISSUE THREAD

**Issue by magestican** [rtc-io/rtc-quickconnect#87]
@DamonOehlman 
I am experiencing an issue when I try to add and remove streams using quickconnect.

If I remove a stream from a participant and add a new one too fast (in the same code block) , I get this exception on the console on chrome 58+

`setRemoteDescription task failed:  DOMException: Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description streams..`

This only started happening after chrome 58 got released, any tips on what could be causing quickconnect to throw this exception?

**Comment by silviapfeiffer** [comment]
This is not an error report by quickconnect, but by the browser. Maybe you're interrupting an existing renegotiation with a new one too quickly?

**Comment by magestican** [comment]
that was indeed the case @silviapfeiffer , i know listen for the RTCPeerConnection renegotiation events to switch streams, thanks!
