### ISSUE TITLE
Failed to execute 'removeTrack' on 'RTCPeerConnection': parameter 1 is not of type 'RTCRtpSender

### ISSUE THREAD

**Issue by rmjahangeer** [rtc-io/rtc-quickconnect#91]
**Browsers and versions affected**
Chrome beta : `Version 64.0.3282.85 (Official Build) beta (64-bit)`
Chrome Canary : `Version 65.0.3323.0 (Official Build) canary (64-bit)`

**Description**
Calling signaller.removeStream causes the exception **`Failed to execute 'removeTrack' on 'RTCPeerConnection': parameter 1 is not of type 'RTCRtpSender`**
also there is no method as `signaller.addTrack()` that can used as per documentation of **RTCPeerConnection**. you can find it here : https://goo.gl/o9Dqhu

**Versions of npm `rtc-quickconnect` tried:**
Old : 5.7.0
Latest : 5.8.1

**Occurs at line**
https://github.com/rtc-io/rtc-quickconnect/blob/c6450fc55c764bb97cbbc1911d20c6dfa0fc6844/index.js#L732

**Steps to reproduce**
Call `signaller.removeStream()`, pass the screen share stream object **(Type of MediaStream)** to it 

**Expected results**
Track/Stream should be removed without throwing an exception

**Actual results**
An exception is thrown.

**Works well as expected in Browser version**
Chrome : `Version 63.0.3239.132 (Official Build) (64-bit)`

**Comment by nathanoehlman** [comment]
Closed by https://github.com/rtc-io/rtc-quickconnect/pull/93 - thanks for the PR 👍
